### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by Kaleidophon** [Kaleidophon/greedy-gerbil#4]
- [ ] Get BoW model working
   - [x] Finish data preparation in regard to image features
   - [x] Adjust model to input data
   - [ ] Training
   - [ ] Evaluation
      - [x] Collect most difficult/easiest questions
      - [ ] Collect most difficult/easiest images
- [ ] Brainstorm other models
- [ ] Report
  - [ ] Initialize report structure
